---
- name: Converge
  hosts: all
  tasks:
    - name: "Include egdoc.vim"
      include_role:
        name: "egdoc.vim"
      vars:
        vim_plugins_repositories:
          - https://github.com/preservim/nerdcommenter
        vim_dotfiles_repo: https://github.com/egdoc/dotfiles
        vim_dotfiles_files:
          - vim
          - vimrc